# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da449b74cfbd04bffadda3005b35a1c274c1cc40c0dd5e776f32cce4776fcd3cb2d987ff152b0b0e32bbb87597a101c7ef25e11c0361d7e04a8ad505b86df942

test:
  secret_key_base: 54203fe51da73ef11ec8c390bbf32251f4b492953008cac59a6d9c43d525f0f42f5f91cc561323bbe7d7f4201225be5cf3790d55bd026ebdc9d38e0852d250a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
